name: tests

#on: [gollum]
on: [push, pull_request]

env:
  SWOW_HAVE_SSL: 1
  SWOW_HAVE_CURL: 1

jobs:
  windows-tests:
    name: PHP ${{ matrix.php-version }} ${{ matrix.ts }} Test on windows-2019
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.3"]
        ts: [ 'ts' ]
      max-parallel: 8
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # TODO: windows varient of setup-php seems to be so slow
      #       shell we add caches?
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          # ini-values: pcov.directory=lib
          # coverage: pcov
          coverage: none
          extensions: curl,openssl,sockets,ffi,pdo,pdo_pgsql
        env:
          phpts: ${{ matrix.ts }}

      - name: Setup composer dependencies
        run: |
          C:\tools\php\php.exe .\.github\workflows\phpunit-adapter.php ${{ matrix.php-version }}
          composer update -o --ignore-platform-reqs

      - name: Build Swow extension
        uses: ./.github/workflows/winext
        with:
          ext-path: ./ext
          tools-path: C:\tools\phpdev
          conf-args: --enable-swow-debug --enable-swow-ssl --enable-swow-curl --enable-debug-pack --enable-swow-pdo-pgsql
          ext-name: swow
          deps: openssl,libcurl,libssh2,zlib,nghttp2,libpq

      - name: Prepare coverage dependencies
        shell: powershell
        run: |
          $headers = @{
            "accept"="application/vnd.github.v3+json";
            "content-type"="application/json";
            "authorization"="Bearer ${{github.token}}";
          }
          # get latest OpenCppCoverage download path
          Write-Host "Fetching latest OpenCppCoverage download path"
          $info = Invoke-WebRequest `
            -UseBasicParsing `
            -Headers $headers `
            -Uri https://api.github.com/repos/OpenCppCoverage/OpenCppCoverage/releases/latest `
              | ConvertFrom-Json
          foreach ($x in $info.assets) {
            if ($x.name.EndsWith('.exe')) {
              Write-Host "Downloading latest OpenCppCoverage"
              $uri = $x.browser_download_url
              Invoke-WebRequest -Uri $uri -OutFile OpenCppCoverage.exe -Headers $headers -UseBasicParsing
              break
            }
          }
          # install OpenCppCoverage
          Write-Host "Installing OpenCppCoverage"
          & .\OpenCppCoverage.exe /SP- /NORESTART /VERYSILENT /DIR=C:\OpenCppCoverage
          # get latest codecov uploader download path
          Write-Host "Fetching latest codecov uploader download path"
          $info = Invoke-WebRequest `
            -UseBasicParsing `
            -Headers $headers `
            -Uri https://api.github.com/repos/codecov/codecov-exe/releases/latest `
              | ConvertFrom-Json
          foreach ($x in $info.assets) {
            if ($x.name.EndsWith('win7-x64.zip')) {
              Write-Host "Downloading latest codecov uploader"
              $uri = $x.browser_download_url
              Invoke-WebRequest -Uri $uri -OutFile codecov.zip -Headers $headers -UseBasicParsing
              break
            }
          }
          # unzip it
          Write-Host "Extracting codecov uploader"
          New-Item C:\Codecov -ItemType Container | Out-Null
          Expand-Archive .\codecov.zip -DestinationPath C:\Codecov

      - name: Run extension tests
        shell: pwsh
        id: test-extension
        continue-on-error: true
        run: |
          & "${env:PGBIN}\initdb.exe" --locale=C -E UTF-8 -U postgres "C:\pgsqldata"
          & "${env:PGBIN}\pg_ctl.exe" -D "C:\pgsqldata" start
          ${env:TEST_SWOW_POSTGRESQL} = "1"
          & C:\OpenCppCoverage\OpenCppCoverage.exe `
            --export_type binary:ext_test.cov `
            --sources ext\include `
            --sources ext\src `
            --excluded_sources ext\deps `
            --cover_children `
            --excluded_line_regex "\s*else.*" `
            --excluded_line_regex "\s*\}.*" `
            --excluded_line_regex "\s*\{\s*" `
            --modules php_swow.dll `
            -- C:\tools\php\php.exe C:\tools\php\composer.phar test-extension

      - name: Run library tests
        shell: pwsh
        id: test-library
        continue-on-error: true
        run: |
          & C:\OpenCppCoverage\OpenCppCoverage.exe `
            --export_type binary:lib_test.cov `
            --sources ext\include `
            --sources ext\src `
            --excluded_sources ext\deps `
            --cover_children `
            --excluded_line_regex "\s*else.*" `
            --excluded_line_regex "\s*\}.*" `
            --excluded_line_regex "\s*\{\s*" `
            --modules php_swow.dll `
            -- C:\tools\php\php.exe C:\tools\php\composer.phar test-library

      - name: Fail if test-extension failed
        if: steps.test-extension.outcome != 'success'
        run: exit 1

      - name: Fail if test-library failed
        if: steps.test-library.outcome != 'success'
        run: exit 1

      - name: Upload coverage tests results
        shell: pwsh
        run: |
          # merge results
          & C:\OpenCppCoverage\OpenCppCoverage.exe `
            --input_coverage=ext_test.cov `
            --input_coverage=lib_test.cov `
            --export_type cobertura:coverage.xml `
            --sources ext\include `
            --sources ext\src `
            --excluded_sources ext\deps `
            --excluded_line_regex "\s*else.*" `
            --excluded_line_regex "\s*\}.*" `
            --excluded_line_regex "\s*\{\s*" `
            --modules php_swow.dll `
            -- C:\tools\php\php.exe -dextension=swow --ri swow
          & C:\Codecov\codecov.exe -f coverage.xml
